stages:
  - test

test_job:
  stage: test
  image: python:3.7
  before_script:
    - pip -V
    - pip install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

  script:
    - echo "test starting"
    - pytest -s tests/test_config.py
    - pytest -s tests/test_route.py
    - echo "test done"