version: "3"

services:
  app:
    build: .
    command: gunicorn app:app -c gunicorn.py
    environment:
    - FLASK_APP=app.py
    - FLASK_ENV=production
    ports:
      - "50001:5000"
    network_mode: bridge
